<footer class="footer">
    <div class="w1200">
        <div class="url">
            友情链接：
            <a href="http://www.ahbofcom.gov.cn/" target="_blank">安徽省商务厅</a>
            <a href="http://www.huiec.org/" target="_blank">安徽省网商协会</a>
            <a href="http://www.ahiib.com/" target="_blank">安徽国际商务职业学院</a>
        </div>
        <p>
            皖ICP备06010770号 版权所有 Copyright © 2018 All Rights Reserve
        </p>
    </div>
</footer>